# Generated by Django 5.0.7 on 2024-08-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_song_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='image',
        ),
    ]
